In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3: 6]

array([4, 5, 6])

In [7]:
b = flat[3:7]
b

array([4, 5, 6, 7])

In [8]:
b[0] = 4444

In [9]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [10]:
b = flat[3:7].copy()
b[0] = 4

In [11]:
b

array([4, 5, 6, 7])

In [12]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [13]:
arr = np.array([1, 54, 23, 53, 45, 76, 29, 2, 13, 94])
arr[[1, 4, 6]]

array([54, 45, 29])

In [14]:
# Multidimensional indexing

In [15]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr[0]

array([1, 2, 3])

In [17]:
arr[1]

array([4, 5, 6])

In [18]:
np.sum(arr, axis=0) #row

array([12, 15, 18])

In [19]:
np.sum(arr, axis=1) #col

array([ 6, 15, 24])

In [20]:
arr[0][1]

np.int64(2)

In [21]:
arr[0, 1]

np.int64(2)

In [22]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [23]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]])

In [24]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
print(arr3d[:, 0, :])

[[1 2 3]
 [7 8 9]]
