In [1]:
import numpy as np

arr = np.array([23, 4, 7, 12])
arr

array([23,  4,  7, 12])

In [2]:
arr.dtype

dtype('int64')

In [3]:
arr.astype("float64")

array([23.,  4.,  7., 12.])

In [4]:
arr2 = np.array([23, 4, 7, 12], dtype="float32")
arr2

array([23.,  4.,  7., 12.], dtype=float32)

In [5]:
arr2.nbytes

16

In [7]:
arr.nbytes

32