In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3 ,4 , 5])
result = arr ** 2
print(result)

[ 1  4  9 16 25]


In [4]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


In [5]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

mean = data.mean(axis=0)
std = data.std(axis=0)

normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
